from __future__ import annotations

from typing import Any, Optional

from .domain import Priority, Status
from .models import Ticket, TicketMessage

TICKET_COLUMNS = "ticket_id, title, status, priority, created_by, created_at"
MESSAGE_COLUMNS = "message_id, ticket_id, message_text, author, created_at"


class RecordNotFound(LookupError):
    pass


class SupportRepository:
    def __init__(self, pool: Any):
        self._pool = pool

    def initialize(self) -> None:
        statements = [
            "CREATE SCHEMA IF NOT EXISTS support",
            """
            CREATE TABLE IF NOT EXISTS support.tickets (
                ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(200) NOT NULL,
                status VARCHAR(20) NOT NULL DEFAULT 'open'
                    CHECK (status IN ('open', 'in_progress', 'resolved')),
                priority VARCHAR(20) NOT NULL DEFAULT 'medium'
                    CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
                created_by VARCHAR(320) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS support.ticket_messages (
                message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ticket_id BIGINT NOT NULL REFERENCES support.tickets(ticket_id),
                message_text TEXT NOT NULL,
                author VARCHAR(320) NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """,
            "CREATE INDEX IF NOT EXISTS tickets_status_created_idx ON support.tickets(status, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS messages_ticket_created_idx ON support.ticket_messages(ticket_id, created_at)",
        ]
        with self._pool.connection() as connection, connection.cursor() as cursor:
            for statement in statements:
                cursor.execute(statement)
            self._seed_if_empty(cursor)

    def _seed_if_empty(self, cursor: Any) -> None:
        cursor.execute("SELECT pg_advisory_xact_lock(hashtext('support_seed_v1'))")
        cursor.execute("SELECT COUNT(*) AS count FROM support.tickets")
        if cursor.fetchone()["count"]:
            return

        samples = [
            (
                "Cannot access the sales dashboard",
                Status.OPEN,
                Priority.HIGH,
                "alex@example.com",
                [
                    ("The dashboard returns an access denied message.", "alex@example.com"),
                    ("We are checking your workspace permissions.", "support@example.com"),
                ],
            ),
            (
                "Scheduled job failed overnight",
                Status.IN_PROGRESS,
                Priority.URGENT,
                "priya@example.com",
                [
                    (
                        "The 2:00 AM pipeline stopped during the transform step.",
                        "priya@example.com",
                    ),
                    ("The support team is reviewing the job logs.", "support@example.com"),
                ],
            ),
            (
                "Request access to customer catalog",
                Status.RESOLVED,
                Priority.MEDIUM,
                "sam@example.com",
                [
                    ("Please grant read access to the customer catalog.", "sam@example.com"),
                    ("Access was granted and confirmed.", "support@example.com"),
                ],
            ),
        ]
        for title, status, priority, created_by, messages in samples:
            cursor.execute(
                """
                INSERT INTO support.tickets (title, status, priority, created_by)
                VALUES (%s, %s, %s, %s)
                RETURNING ticket_id
                """,
                (title, status.value, priority.value, created_by),
            )
            ticket_id = cursor.fetchone()["ticket_id"]
            for message_text, author in messages:
                cursor.execute(
                    """
                    INSERT INTO support.ticket_messages (ticket_id, message_text, author)
                    VALUES (%s, %s, %s)
                    """,
                    (ticket_id, message_text, author),
                )

    def list_tickets(self, status: Optional[Status] = None) -> list[Ticket]:
        query = f"SELECT {TICKET_COLUMNS} FROM support.tickets"
        params = None
        if status is not None:
            query += " WHERE status = %s"
            params = (status.value,)
        query += " ORDER BY created_at DESC, ticket_id DESC"
        rows = self._fetchall(query, params)
        return [Ticket.from_row(row) for row in rows]

    def get_ticket(self, ticket_id: int) -> Ticket:
        row = self._fetchone(
            f"SELECT {TICKET_COLUMNS} FROM support.tickets WHERE ticket_id = %s",
            (ticket_id,),
        )
        if row is None:
            raise RecordNotFound(f"Ticket {ticket_id} does not exist.")
        return Ticket.from_row(row)

    def get_messages(self, ticket_id: int) -> list[TicketMessage]:
        rows = self._fetchall(
            f"SELECT {MESSAGE_COLUMNS} FROM support.ticket_messages WHERE ticket_id = %s ORDER BY created_at, message_id",
            (ticket_id,),
        )
        return [TicketMessage.from_row(row) for row in rows]

    def create_ticket(self, *, title: str, priority: Priority, created_by: str) -> Ticket:
        row = self._fetchone(
            f"""
            INSERT INTO support.tickets (title, priority, created_by)
            VALUES (%s, %s, %s)
            RETURNING {TICKET_COLUMNS}
            """,
            (title, priority.value, created_by),
        )
        return Ticket.from_row(row)

    def add_message(self, *, ticket_id: int, message_text: str, author: str) -> TicketMessage:
        row = self._fetchone(
            f"""
            INSERT INTO support.ticket_messages (ticket_id, message_text, author)
            VALUES (%s, %s, %s)
            RETURNING {MESSAGE_COLUMNS}
            """,
            (ticket_id, message_text, author),
        )
        return TicketMessage.from_row(row)

    def update_status(self, ticket_id: int, status: Status) -> Ticket:
        row = self._fetchone(
            f"""
            UPDATE support.tickets SET status = %s WHERE ticket_id = %s
            RETURNING {TICKET_COLUMNS}
            """,
            (status.value, ticket_id),
        )
        if row is None:
            raise RecordNotFound(f"Ticket {ticket_id} does not exist.")
        return Ticket.from_row(row)

    def ticket_statistics(self) -> dict[str, int]:
        rows = self._fetchall(
            "SELECT status, COUNT(*) AS count FROM support.tickets GROUP BY status"
        )
        stats = {"total": 0, **{status.value: 0 for status in Status}}
        for row in rows:
            stats[row["status"]] = row["count"]
            stats["total"] += row["count"]
        return stats

    def _fetchall(self, query: str, params: Any = None) -> list[Any]:
        with self._pool.connection() as connection, connection.cursor() as cursor:
            cursor.execute(query, params)
            return cursor.fetchall()

    def _fetchone(self, query: str, params: Any = None) -> Any:
        with self._pool.connection() as connection, connection.cursor() as cursor:
            cursor.execute(query, params)
            return cursor.fetchone()
